### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by hughperkins** [datsfain/EditorCools#1]
Hi, Cool project :)

What are the installation instructions for the simplest case? Like, without adding in examples, samples, etc?

Note: preference that I can simply download eg a zip file from somewhere, unzip it, and drag the contents into my project.

**Comment by hughperkins** [comment]
(maybe you can create a drop-in managed .dll or similar perhaps? Right now, I feel the easiest way for me to install your scripts is to clone your repo, then drag the bits I want into my project)

**Comment by datsfain** [comment]
Hi, thank you, I have added release .unitypackage, you can simply download it and import folders that you would like from package import dialog in unity. Here you can see more info about importing package, it should take few clicks:
https://docs.unity3d.com/560/Documentation/Manual/AssetPackages.html
sorry for the delay.

**Comment by datsfain** [comment]
https://github.com/datsfain/EditorCools/releases/tag/1.0.0 here is link for the release

**Comment by hughperkins** [comment]
Thank you!
