### ISSUE TITLE
Buttons doesnt show up?

### ISSUE THREAD

**Issue by HajiyevEl** [datsfain/EditorCools#2]
Hi, thanks for your hard work! 

I have a problem with button attributes. Opened sample scene, slider and options1-2 work fine, but buttons doesn't show up. 
Unity 2023.2.0f1

**Comment by datsfain** [comment]
Hi, i will download the 2023.2.0f1 version and check it out, thanks for
notifying me!

**Comment by datsfain** [comment]
Hi, I opened my project in Unity 2023.2.0f1 and everything seems to be
working fine, could you show me a screenshot, or if you have any errors in
the console?

**Comment by datsfain** [comment]
[image: image.png]
Here is my screenshot

**Comment by HajiyevEl** [comment]
![Screenshot 2024-03-13 122603](https://github.com/datsfain/EditorCools/assets/70325881/2bbb0ce3-2f44-4d2d-b7f4-9cbbc6feb0cf)
![Screenshot 2024-03-13 122733](https://github.com/datsfain/EditorCools/assets/70325881/7c791d3a-cb9a-4d4f-b7d3-9743dbcd1bef)
Hi again, thanks for replying! After importing package, opened test scene. No script modifications done, no items in scene changed. No warnings at all.

**Comment by HajiyevEl** [comment]
BTW, how should i get selected value from dropdown?

**Comment by datsfain** [comment]
You can get selected value from the string variable that has Dropdown
attribute.

**Comment by HajiyevEl** [comment]
Sorry to trouble you, all works fine now. There was conflict between my other inspector package (vInspector), after disabling it all works fine now. Thanks!
